name: Create new branch

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: Release version
        required: true
        type: string

jobs:
  create_release_branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create branch
        run: |
          set -x -e

          release_version="${{ inputs.release_version }}"
          echo "release version: $release_version"

          branch_name="release/$release_version"
          git checkout -b $branch_name

          sed -i "s/0.0.1/$release_version/g" _version.py
          cat _version.py

          git add _version.py
          git config --global user.name 'Zhengfei Wang'
          git config --global user.email 'wangzhengfei.chn@outlook.com'
          git commit -m "create branch for version $release_version"
          git push --set-upstream origin $branch_name
