name: test-merge-main

on:
  pull_request_target:
    branches:
      - main
  workflow_dispatch:

jobs:
  merge_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - name: merge main
        run: |
          echo ${{ github.event.pull_request.head.sha }}
          echo ${{ github.ref }}
          git status
          git pull origin main
          git merge main
          git status
        id: merge_main
        shell: bash -el {0}
